const ipcEvents = {
    GET_INSTALLED_META : ":GET_INSTALLED_META",
    INSTALLED_META : ":INSTALLED_META",
    HOST_USERNAME :":HOST_USERNAME",
    GET_HOST_USERNAME : ":GET_HOST_USERNAME",
    SET_AUTO_LOGIN_COMPUTER : ":SET_AUTO_LOGIN_COMPUTER",
    REBOT : ":REBOT",
    SET_AUTO_STARTUP : ":SET_AUTO_STARTUP",
    DISABLE : ":DISABLE"
  
  
}

module.exports =  ipcEvents